spring:
  application:
    name: neoin-cloud-gateway
server:
  port: ${GATEWAY_PORT:8088}
  servlet:
    context-path: /gateway
eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      registerWithEureka: true
      fetchRegistry: true
  instance:
    preferIpAddress: true
