spring:
  application:
    name: neoin-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: shop
          uri: lb://test-service
          predicates:
            - Path=/neo/**
server:
  port: ${GATEWAY_PORT:8088}
  servlet:
    context-path: /gateway
eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      registerWithEureka: true
      fetchRegistry: true
  instance:
    preferIpAddress: true